In [13]:
# load necessary modules
import numpy as np 
from scipy.integrate import odeint
import os, sys 
from pathlib import Path
from os.path import dirname, realpath
script_dir = Path(dirname(realpath('.')))
module_dir = str(script_dir)
sys.path.insert(0, module_dir + '/modules')
import utility as ut
import matplotlib.pyplot as plt
from joblib import Parallel, delayed
import time
import KS

save_folder='../data/KS-trajectories'


#------------------------------------------------------------------------------
# define data and initialize simulation
L    = 200/(2*np.pi)
N    = 512
dt   = 0.25
ninittransients = 10000
tend = 50000 + ninittransients  #50000
dns  = KS.KS(L=L, N=N, dt=dt, tend=tend)


N_data_train = 100000
N_data_test = 100000
dl_max = 20000
pl_max = 20000


#------------------------------------------------------------------------------
# simulate initial transient
dns.simulate()
# convert to physical space
dns.fou2real()


u = dns.uu[ninittransients:]

print(u.shape)

N_train_max = int(u.shape[0])
print('Max N_train:')
print(N_train_max)



[u_train, u_test, _] = np.split(u, [N_data_train, N_data_train+N_data_test], axis=0)
print("Traing data shape: ")
print(u_test.shape)
print(u_train.shape)

np.save('{}/{}.npy'.format(save_folder, f'train{1}'), u_train.T)

Time taken by simulate is 12.4794 seconds
(230001, 512)
Max N_train:
230001
Traing data shape: 
(100000, 512)
(100000, 512)


In [14]:
# generate test data
u_test = generate_data(0, int(500*1000))
test = u_test[1:].reshape(500,-1, 512)
test = np.moveaxis(test, -1, -2)
np.random.shuffle(test)
np.save('{}/{}.npy'.format(save_folder, f'test'), test)
test.shape

NameError: name 'generate_data' is not defined

In [5]:
# generate training data
for i in [0]:
    u = generate_data(i, int(2e5)).T
    np.save('{}/{}.npy'.format(save_folder, f'train{i+1}'), u)

Time taken by simulate is 0.0157 seconds
Time taken by generate_data is 0.0257 seconds


In [8]:
i = 0
u = np.load('{}/{}.npy'.format(save_folder, f'train{i+1}'))

In [3]:
u.dtype

dtype('float64')

In [15]:
np.save('{}/{}.npy'.format(save_folder, f'test'), test)

In [17]:
np.random.shuffle(test)

In [18]:
np.save('{}/{}.npy'.format(save_folder, f'test'), test[:500, :, :])

In [6]:
u

array([], shape=(512, 0), dtype=float64)

In [12]:
np.real(np.fft.ifft([0, 4, 0, 0])).dtype

dtype('float64')

In [25]:
B = 4
u = np.random.normal(size=(200, 3))
v = np.random.normal(size=(200, 3)) 
u1 = u.reshape(-1, 3*B)
u.shape

(200, 3)

In [27]:
u[:B]

array([[-0.13386272,  0.15371307,  0.93080103],
       [ 0.23913657,  0.67049533, -0.6439737 ],
       [ 0.18181233, -1.41854032, -0.92043787],
       [-0.3472285 , -0.42383813,  2.708355  ]])

In [28]:
u1[0]

array([-0.13386272,  0.15371307,  0.93080103,  0.23913657,  0.67049533,
       -0.6439737 ,  0.18181233, -1.41854032, -0.92043787, -0.3472285 ,
       -0.42383813,  2.708355  ])

In [33]:
from torch import nn 
import torch

In [36]:
a = .__class__

In [38]:
a(torch.tensor(u)) - nn.Parameter(torch.tensor(u))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0

In [40]:
2**(-19)

1.9073486328125e-06

In [41]:
u = np.random.normal(size=(200, 3))

In [42]:
v = np.array([e for i, e in enumerate(u) if i%4==0])

In [43]:
v.shape

(50, 3)

In [46]:
0.91/(0.02/4)

182.0

In [47]:
182*20

3640

In [10]:
u

array([], shape=(512, 0), dtype=float64)