In [1]:
# load necessary modules
import numpy as np 
from scipy.integrate import odeint
import os, sys 
from pathlib import Path
from os.path import dirname, realpath
script_dir = Path(dirname(realpath('.')))
module_dir = str(script_dir)
sys.path.insert(0, module_dir + '/modules')
import utility as ut
import matplotlib.pyplot as plt
from joblib import Parallel, delayed
import time
import KS

save_folder='../data/KS-trajectories'

@ut.timer
def generate_data(i, N_data):
    # define data and initialize simulation
    L    = 200
    N    = 512
    dt   = 0.25 / (i+1)
    ninittransients = 10000
    tend = 50000 + ninittransients  #50000
    dns  = KS.KS(L=L, N=N, dt=dt, nsteps=N_data + ninittransients, tend=tend)
    dl_max = 20000
    pl_max = 20000
    # simulate initial transient
    dns.simulate()
    # convert to physical space
    dns.fou2real()
    return dns.uu[ninittransients:]


In [6]:
# generate test data
u_test = generate_data(0, int(500*1000))
test = u_test[1:].reshape(500,-1, 512)
test = np.moveaxis(test, -1, -2)
np.random.shuffle(test)
np.save('{}/{}.npy'.format(save_folder, f'test'), test)
test.shape

Time taken by simulate is 26.7176 seconds
Time taken by generate_data is 30.3343 seconds


(500, 512, 1000)

In [4]:
# generate training data
for i in [0, 1, 3, 7, 15]:
    u = generate_data(i, int(2e5)).T
    np.save('{}/{}.npy'.format(save_folder, f'train{i+1}'), u)

Time taken by simulate is 11.0784 seconds
Time taken by generate_data is 11.5839 seconds
Time taken by simulate is 11.1970 seconds
Time taken by generate_data is 11.6956 seconds
Time taken by simulate is 10.9714 seconds
Time taken by generate_data is 11.4772 seconds
Time taken by simulate is 11.2015 seconds
Time taken by generate_data is 11.7065 seconds
Time taken by simulate is 11.1289 seconds
Time taken by generate_data is 11.6378 seconds


In [8]:
i = 0
u = np.load('{}/{}.npy'.format(save_folder, f'train{i+1}'))

In [3]:
u.dtype

dtype('float64')

In [15]:
np.save('{}/{}.npy'.format(save_folder, f'test'), test)

In [17]:
np.random.shuffle(test)

In [18]:
np.save('{}/{}.npy'.format(save_folder, f'test'), test[:500, :, :])

In [20]:
test

array([[[-2.26854515e+00, -2.17145443e+00, -2.07884598e+00, ...,
         -6.08896613e-01, -5.97859740e-01, -5.88010252e-01],
        [-2.36316681e+00, -2.28098011e+00, -2.20200205e+00, ...,
         -5.15246630e-01, -5.09794414e-01, -5.05712092e-01],
        [-2.36526513e+00, -2.29930234e+00, -2.23551989e+00, ...,
         -4.36226189e-01, -4.35150206e-01, -4.35517848e-01],
        ...,
        [-1.37795687e+00, -1.25995934e+00, -1.15035796e+00, ...,
         -9.74174738e-01, -9.41478074e-01, -9.08797979e-01],
        [-1.77363563e+00, -1.65717292e+00, -1.54796171e+00, ...,
         -8.39642167e-01, -8.14677835e-01, -7.90218115e-01],
        [-2.07260180e+00, -1.96355307e+00, -1.86038828e+00, ...,
         -7.17235684e-01, -6.99605346e-01, -6.82872653e-01]],

       [[-1.26261979e-01, -6.98286593e-02, -1.97832882e-02, ...,
          8.00912201e-01,  7.18284369e-01,  6.42917573e-01],
        [-1.51104867e-01, -1.02054760e-01, -5.96638918e-02, ...,
          1.01456833e+00,  9.31222022e

In [12]:
np.real(np.fft.ifft([0, 4, 0, 0])).dtype

dtype('float64')

In [25]:
B = 4
u = np.random.normal(size=(200, 3))
v = np.random.normal(size=(200, 3)) 
u1 = u.reshape(-1, 3*B)
u.shape

(200, 3)

In [27]:
u[:B]

array([[-0.13386272,  0.15371307,  0.93080103],
       [ 0.23913657,  0.67049533, -0.6439737 ],
       [ 0.18181233, -1.41854032, -0.92043787],
       [-0.3472285 , -0.42383813,  2.708355  ]])

In [28]:
u1[0]

array([-0.13386272,  0.15371307,  0.93080103,  0.23913657,  0.67049533,
       -0.6439737 ,  0.18181233, -1.41854032, -0.92043787, -0.3472285 ,
       -0.42383813,  2.708355  ])

In [33]:
from torch import nn 
import torch

In [36]:
a = .__class__

In [38]:
a(torch.tensor(u)) - nn.Parameter(torch.tensor(u))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0

In [40]:
2**(-19)

1.9073486328125e-06

In [41]:
u = np.random.normal(size=(200, 3))

In [42]:
v = np.array([e for i, e in enumerate(u) if i%4==0])

In [43]:
v.shape

(50, 3)

In [46]:
0.91/(0.02/4)

182.0

In [47]:
182*20

3640