In [9]:
import torch
import numpy as np 


a = np.random.normal(size=(10, 3)) 
b = np.random.normal(size=(10, 3))
a, b

(array([[-0.88549151,  0.02314001,  2.5057889 ],
        [ 0.99383763,  0.06307978,  0.36252912],
        [-1.18525372,  0.06397619,  2.62514198],
        [ 1.20569942, -0.25459763,  0.50811901],
        [-0.65930051,  0.53717853,  0.4166613 ],
        [-0.88657635, -1.2868348 , -1.14774624],
        [-0.74319601, -1.13092466, -0.46351233],
        [-0.09585334, -0.35170502,  0.90040282],
        [ 0.47075385,  0.13943996,  0.59315315],
        [ 1.72545887,  0.59822993,  0.94042633]]),
 array([[ 2.30240124,  0.51525167,  0.24321379],
        [ 1.44899477,  1.04334995, -0.82041705],
        [-0.82259631, -0.31373151, -0.71123297],
        [ 0.3736765 ,  1.07661918,  1.09561405],
        [-1.7678816 , -0.46386721,  0.40602504],
        [-1.66964773,  0.76881438, -1.8708472 ],
        [-0.843988  , -0.69816067,  0.9000977 ],
        [-0.18627291, -0.26172435, -1.42207265],
        [-0.03557598,  2.71038555,  0.05541821],
        [-1.52736647, -0.37197663,  0.17798572]]))

In [13]:
c = np.sign(a[:, -1]*b[:, -1])[:, np.newaxis]
c,b*c

(array([[ 1.],
        [-1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.],
        [ 1.]]),
 array([[ 2.30240124,  0.51525167,  0.24321379],
        [-1.44899477, -1.04334995,  0.82041705],
        [ 0.82259631,  0.31373151,  0.71123297],
        [ 0.3736765 ,  1.07661918,  1.09561405],
        [-1.7678816 , -0.46386721,  0.40602504],
        [-1.66964773,  0.76881438, -1.8708472 ],
        [ 0.843988  ,  0.69816067, -0.9000977 ],
        [ 0.18627291,  0.26172435,  1.42207265],
        [-0.03557598,  2.71038555,  0.05541821],
        [-1.52736647, -0.37197663,  0.17798572]]))

In [7]:
c

array([[ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.]])